version: '3.1'

services:
  pg_db_test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_test
    ports:
      - ${POSTGRES_PORT:-5432}:5432